name: Benchmark Matrix

on:
   workflow_dispatch:
     inputs:
      ITERATIONS:
        description: 'Test iterations, default 3'
        required: false

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        DBNAME: [ "chdb", "duckdb", "glaredb", "databend", "datafusion"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest
        poetry lock --no-update
        poetry install
        wget -q https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet
#    - name: Workflow Telemetry
#      uses: runforesight/workflow-telemetry-action@v1.8.7     
    - name: Test with poetry
      env:
        ITERATIONS: ${{ github.event.inputs.ITERATIONS || 3 }}
        DBNAME: ${{ matrix.DBNAME }}
      run: |
        poetry run python3 benchmark.py > /tmp/report.txt
    - name: Summary Report
      run: |
        echo "### ${{ matrix.DBNAME }}" >> $GITHUB_STEP_SUMMARY
        cat /tmp/report.txt >> $GITHUB_STEP_SUMMARY
